import type { Account, Message } from "./types";

const systemMailboxes = [
  { id: "inbox", label: "받은편지함", kind: "inbox" as const, unread: 12 },
  { id: "starred", label: "중요 표시", kind: "starred" as const },
  { id: "sent", label: "보낸편지함", kind: "sent" as const },
  { id: "drafts", label: "임시보관함", kind: "drafts" as const, unread: 2 },
  { id: "archive", label: "보관함", kind: "archive" as const },
  { id: "spam", label: "스팸", kind: "spam" as const, unread: 3 },
  { id: "trash", label: "휴지통", kind: "trash" as const },
];

export const accounts: Account[] = [
  {
    id: "personal",
    email: "jooseho@gmail.com",
    label: "개인 계정",
    initials: "JS",
    unread: 12,
    storage: "6.2 / 15 GB",
    mailboxes: [
      ...systemMailboxes,
      {
        id: "work",
        label: "Work",
        kind: "folder",
        children: [
          { id: "clients", label: "Clients", kind: "folder", unread: 4 },
          { id: "internal", label: "Internal", kind: "folder" },
        ],
      },
    ],
  },
  {
    id: "ops",
    email: "ops@company.com",
    label: "업무 계정",
    initials: "OP",
    unread: 7,
    storage: "3.8 / 10 GB",
    mailboxes: [
      { ...systemMailboxes[0], unread: 7 },
      ...systemMailboxes.slice(1),
      {
        id: "team",
        label: "Team",
        kind: "folder",
        children: [{ id: "infra", label: "Infra", kind: "folder", unread: 2 }],
      },
    ],
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "이서연",
    senderEmail: "seoyeon.lee@company.com",
    initials: "이",
    subject: "회의 자료 공유드립니다 (Q3 로드맵)",
    snippet: "내일 회의 전에 검토 부탁드릴 자료입니다",
    time: "오전 9:14",
    fullDate: "2026년 7월 2일 (목) 오전 9:14",
    unread: true,
    flagged: true,
    hasAttachment: true,
    remoteImagesBlocked: true,
    body: [
      "주호님, 안녕하세요.",
      "내일 오전 회의 전에 미리 검토해 주셨으면 하는 Q3 로드맵 초안을 공유드립니다. 지난 스프린트 회고에서 나온 피드백을 반영해 우선순위를 다시 정리했고, 특히 MIME 파싱 / charset 변환 관련 백엔드 작업을 2주 앞당겼습니다.",
      "핵심 변경 사항은 다음과 같습니다.",
      "The full breakdown is in the attached PDF. Please add comments directly on the doc — 회의에서는 열린 이슈 위주로만 논의하려고 합니다.",
      "감사합니다.\n이서연 드림",
    ],
    bullets: [
      "데스크톱 3-pane 셸 & 계정 스위처 — 7월 3주차 완료 목표",
      "읽기창 MIME 렌더링 (EUC-KR / ISO-2022-JP 포함) — 8월 1주차",
      "Compose 오버레이 & 모바일 드릴다운 — 8월 3주차",
    ],
    link: "https://docs.company.com/joomail/q3-roadmap",
    attachments: [
      { name: "Q3_Roadmap_v2.pdf", size: "2.4 MB", type: "pdf" },
      { name: "timeline_chart.png", size: "712 KB", type: "image" },
    ],
  },
  {
    id: "m2",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "GitHub",
    senderEmail: "notifications@github.com",
    initials: "GH",
    subject: "[joomail/webmail] Fix MIME charset decoding (#142)",
    snippet: "kimjh approved these changes · ready to merge",
    time: "오전 8:52",
    fullDate: "2026년 7월 2일 (목) 오전 8:52",
    unread: true,
    body: [
      "Pull request #142 has been approved.",
      "The charset decoding fixture now covers EUC-KR and ISO-2022-JP samples. CI results are available in the checks tab.",
    ],
  },
  {
    id: "m3",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "김민준",
    senderEmail: "minjun.kim@company.com",
    initials: "김",
    subject: "Re: 서버 이전 일정 관련 문의",
    snippet: "7월 15일 새벽 점검으로 진행하면 될 것 같습니다",
    time: "오전 8:30",
    fullDate: "2026년 7월 2일 (목) 오전 8:30",
    unread: true,
    body: ["7월 15일 새벽 점검으로 진행하면 될 것 같습니다.", "변경 공지는 오늘 오후에 초안 작성해 두겠습니다."],
  },
  {
    id: "m4",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "AWS Billing",
    senderEmail: "no-reply-aws@amazon.com",
    initials: "AWS",
    subject: "AWS bill for June 2026 is available",
    snippet: "Your total for June 2026 is $214.37",
    time: "오전 7:05",
    fullDate: "2026년 7월 2일 (목) 오전 7:05",
    unread: false,
    hasAttachment: true,
    body: ["Your AWS bill for June 2026 is now available.", "Estimated total: $214.37."],
  },
  {
    id: "m5",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "박지호",
    senderEmail: "jiho.park@company.com",
    initials: "박",
    subject: "[공유] 신규 클라이언트 온보딩 체크리스트",
    snippet: "이번 주 온보딩 예정 3곳 준비사항 정리했습니다",
    time: "어제",
    fullDate: "2026년 7월 1일 (수) 오후 5:42",
    unread: true,
    body: ["신규 클라이언트 온보딩 체크리스트를 공유합니다.", "필요한 계정과 DNS 설정 항목을 먼저 확인해주세요."],
  },
  {
    id: "m6",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "Vercel",
    senderEmail: "notifications@vercel.com",
    initials: "VC",
    subject: "Deployment ready: joomail-web",
    snippet: "build completed in 47s",
    time: "어제",
    fullDate: "2026년 7월 1일 (수) 오후 3:21",
    unread: false,
    body: ["Deployment ready: joomail-web", "Production build completed in 47 seconds."],
  },
  {
    id: "m7",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "국민은행",
    senderEmail: "notice@kb.co.kr",
    initials: "국",
    subject: "[Web발신] 출금 500,000원 알림",
    snippet: "잔액 1,842,300원 · 자세한 내용 확인",
    time: "어제",
    fullDate: "2026년 7월 1일 (수) 오전 11:10",
    unread: false,
    body: ["출금 알림입니다.", "잔액 1,842,300원."],
  },
  {
    id: "m8",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "Slack",
    senderEmail: "feedback@slack.com",
    initials: "SL",
    subject: "New messages in #eng-platform",
    snippet: "@channel mentioned you in a thread",
    time: "6월 30일",
    fullDate: "2026년 6월 30일 (화) 오후 6:03",
    unread: false,
    body: ["You have new messages in #eng-platform.", "@channel mentioned you in a thread."],
  },
  {
    id: "m9",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "정승호",
    senderEmail: "seungho.jung@company.com",
    initials: "정",
    subject: "여름 휴가 일정 조율 건",
    snippet: "다들 8월 초 어떠세요? 가능한 날짜 남겨주세요",
    time: "6월 30일",
    fullDate: "2026년 6월 30일 (화) 오후 2:18",
    unread: false,
    body: ["여름 휴가 일정을 조율하려고 합니다.", "가능한 날짜를 오늘까지 남겨주세요."],
  },
  {
    id: "m10",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "LinkedIn",
    senderEmail: "messages-noreply@linkedin.com",
    initials: "LI",
    subject: "You appeared in 9 searches this week",
    snippet: "See who is looking at your profile",
    time: "6월 29일",
    fullDate: "2026년 6월 29일 (월) 오전 9:42",
    unread: false,
    body: ["You appeared in 9 searches this week.", "See who is looking at your profile."],
  },
  {
    id: "m11",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "넷플릭스",
    senderEmail: "info@account.netflix.com",
    initials: "넷",
    subject: "이번 주 새로 올라온 콘텐츠",
    snippet: "회원님을 위한 추천작 — 지금 확인해보세요",
    time: "6월 28일",
    fullDate: "2026년 6월 28일 (일) 오후 7:00",
    unread: false,
    body: ["이번 주 새로 올라온 콘텐츠를 확인해보세요."],
  },
  {
    id: "m12",
    accountId: "ops",
    mailboxId: "inbox",
    sender: "Postfix Report",
    senderEmail: "postmaster@company.com",
    initials: "PR",
    subject: "Daily mail delivery report",
    snippet: "Received 1,204 · deferred 3 · bounced 0",
    time: "오전 6:00",
    fullDate: "2026년 7월 2일 (목) 오전 6:00",
    unread: true,
    body: ["Daily delivery report is ready.", "Received 1,204 messages. Deferred 3. Bounced 0."],
  },
  {
    id: "qa-long-overflow",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "International Platform Reliability Notifications With A Very Long Sender Name",
    senderEmail: "platform-reliability-notifications-extremely-long-address@example.internal.company",
    initials: "IP",
    subject: "QA overflow: this subject is intentionally long to verify row truncation, reading pane title wrapping, and mobile header containment without overlapping adjacent controls",
    snippet: "This snippet is intentionally verbose and repetitive so list rows must preserve fixed anchors and truncate calmly in every viewport without resizing controls or covering icons.",
    time: "오전 5:45",
    fullDate: "2026년 7월 2일 (목) 오전 5:45",
    unread: true,
    body: [
      "This QA message intentionally uses very long sender, address, subject, and snippet values.",
      "It should stay inside list rows and reading surfaces without overlapping controls.",
    ],
  },
  {
    id: "qa-many-attachments",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "Design QA",
    senderEmail: "design-qa@example.com",
    initials: "DQ",
    subject: "QA attachment wrapping with many long file names",
    snippet: "Attachment chips should wrap without breaking the reading pane layout",
    time: "오전 5:30",
    fullDate: "2026년 7월 2일 (목) 오전 5:30",
    unread: false,
    hasAttachment: true,
    body: ["Please verify that the attachment area wraps consistently with many files and long names."],
    attachments: [
      { name: "quarterly-roadmap-final-review-notes.pdf", size: "1.2 MB", type: "pdf" },
      { name: "timeline-chart-large-retina.png", size: "842 KB", type: "image" },
      { name: "customer-import-template-v2026-07.csv", size: "96 KB", type: "file" },
      { name: "mailbox-migration-risk-register.xlsx", size: "420 KB", type: "file" },
      { name: "smtp-delivery-screenshot-before-after.png", size: "1.8 MB", type: "image" },
      { name: "security-review-attachment-policy.pdf", size: "980 KB", type: "pdf" },
      { name: "very-long-file-name-that-should-truncate-inside-the-chip-without-resizing-layout.txt", size: "12 KB", type: "file" },
    ],
  },
  {
    id: "qa-quoted",
    accountId: "personal",
    mailboxId: "inbox",
    sender: "Reply QA",
    senderEmail: "reply-qa@example.com",
    initials: "RQ",
    subject: "QA quoted conversation expansion",
    snippet: "Quoted blocks should be collapsed by default and expandable for review",
    time: "오전 5:15",
    fullDate: "2026년 7월 2일 (목) 오전 5:15",
    unread: false,
    body: [
      "Here is the current reply content that should remain visible.",
      "On Wed, Jul 1, 2026 at 4:12 PM Original Sender wrote:",
      "> Previous message line one.",
      "> Previous message line two with enough text to wrap and verify quoted block spacing.",
    ],
  },
];
